name: root
dependencies:
- cffi=1.2.1=py35_0
- conda=3.19.1=py35_0
- conda-env=2.4.5=py35_0
- cython=0.23.4=py35_0
- freetype=2.5.5=0
- h5py=2.5.0=np110py35_4
- hdf5=1.8.15.1=2
- jbig=2.1=0
- jpeg=8d=0
- libffi=3.0.13=0
- libgfortran=1.0=0
- libpng=1.6.17=0
- libsodium=1.0.3=0
- libtiff=4.0.6=1
- mkl=11.3.1=0
- numexpr=2.4.6=np110py35_1
- numpy=1.10.4=py35_0
- openssl=1.0.2f=0
- pillow=3.1.1=py35_0
- pip=8.0.2=py35_0
- pycosat=0.6.1=py35_0
- pycparser=2.14=py35_0
- pycrypto=2.6.1=py35_0
- pytables=3.2.2=np110py35_0
- python=3.5.1=0
- pyyaml=3.11=py35_1
- pyzmq=15.2.0=py35_0
- readline=6.2=2
- requests=2.9.1=py35_0
- scipy=0.17.0=np110py35_1
- setuptools=19.6.2=py35_0
- six=1.10.0=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- toolz=0.7.4=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- yaml=0.1.6=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - fuel (/home/vanmerb/fuel)==0.1.1
  - mimir (/home/vanmerb/mimir)==0.1.dev1
  - picklable-itertools (/home/vanmerb/picklable-itertools)==0.1.1
  - platoon (/home/vanmerb/platoon)==0.5.0
  - posix-ipc==1.0.0
  - progressbar2==3.6.0
  - tables==3.2.2
  - theano (/home/vanmerb/Theano)==0.8.0.dev0

